#!/usr/bin/env bash
#script that display num 1 to 100
num=1
for num in {1..100}
do
	echo $num
if ! ((num%15))
  then 
	echo "FizzBuzz"
elif ! ((num%3))
  then 
	echo "Fizz"
elif ! ((num%5)) 
  then 
	echo "Buzz"

fi
 ((num++))
done

