#!/usr/bin/env bash
#Script that loops from 1 to 10
counter=1
while [ $counter -le 10 ]
do
	echo "Best School"
    if [ $counter = 4 ] 
	then
		break

	elif [ $counter = 4 ]
	then
		
		echo "bad luck"
		else
			continue

	fi
     if [ $counter = 8 ]
     then
	    break 
	 elif [ $counter = 8 ]
	 then
		 echo "good luck"
	 else
		 continue

     fi     

	((counter++))
done
