#!/usr/bin/env bash
#Script that timer
hours=0
min=1
while [[ $hours -le 12 ]]
do
 if [ $min = 1 ]
 then
	 echo "Hour: 0"
 elif [ $hours = 0 ]
 then 
	 echo "Hour: 1"
 else
	 echo $hours

 fi
 ((hours++))

while [[ $min -le 59 ]]
do
	echo $min
 ((min++)) 

done
done 
