#!/usr/bin/env bash
#Script that display file info
file=School
   if [ -e "$file" ]
   then 
	echo "file $file exist "
   else
	echo "file $file does not exist"
   fi

   if [ -e "$file" ] && [ -s "$file" ]
   then
	echo "file $file is not empty"
   elif [ -e "$file" ] || [ -s "$file" ]
   then
	echo "file $file is empty"
   else 
	if [ -f "$file" ]
	then 
	echo "file $file is a regular file"
	fi	
   fi
