#!/usr/bin/env bash
#Script that display file info
file=school
if [ -e "$file" ]
then 
	echo "$file file exist "
elif ! [ -e "$file" ]
then
	echo "$file file does not exist"

fi

if [ -e "$file" ] && [ -s "$file" ]
   then
	echo "$file file is not empty"
   elif [ -e "$file" ] || [ -s "$file" ]
   then
	echo "$file file is empty"
fi

if [ -f "$file" ]
	then 
	echo "$file is a regular file"
	fi	
 
